runtime: python38

env_variables:
  DB_USER: "fridge"         # Ersetze dies durch deinen tatsächlichen Datenbankbenutzer
  DB_PASS: "fridge"     # Ersetze dies durch dein tatsächliches Datenbankpasswort
  DB_HOST: "34.89.166.195"       # Öffentliche IP-Adresse der Datenbank
  DB_NAME: "Smartfridge"                # Der Name der Datenbank, die du verwenden möchtest
  INSTANCE_CONNECTION_NAME: "smart-fridge-sopra:europe-west3:sopra-db-smartfridge" # Verbindungsname deiner Cloud**

handlers:
  - url: /.*
    script: auto
